// <auto-generated />
using System;
using Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(OneProDbContext))]
    partial class OneProDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Contracts.Group.Responses.GroupResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NamaDivisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaPerusahaan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GroupResponses");
                });

            modelBuilder.Entity("Core.Contracts.Ric.Responses.FormRicApprovalResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdApprover")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFormRic")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FormRicApprovalResponses");
                });

            modelBuilder.Entity("Core.Contracts.Ric.Responses.FormRicHistoryResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditedFields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdEditor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFormRic")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FormRicHistoryResponses");
                });

            modelBuilder.Entity("Core.Contracts.Ric.Responses.FormRicResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternatifSolusi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AsIsProcessRasciFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BrConfirm")
                        .HasColumnType("bit");

                    b.Property<string>("DampakMasalah")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EcsConfirm")
                        .HasColumnType("bit");

                    b.Property<string>("ExcpectedCompletionTargetFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaktorPenyebabMasalah")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasilSetelahPerbaikan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hastag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permasalahan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PotensiValueCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SarmConfirm")
                        .HasColumnType("bit");

                    b.Property<string>("SolusiSaatIni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToBeProcessBusinessRasciKkiFile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FormRicResponses");
                });

            modelBuilder.Entity("Core.Contracts.Ric.Responses.ReviewFormRicResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Catatan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdFormRic")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleReview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReviewFormRicResponses");
                });

            modelBuilder.Entity("Core.Contracts.Ric.Responses.UndanganFormRicResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdBr")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdGroupUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UndanganFormRicResponses");
                });

            modelBuilder.Entity("Core.Contracts.Users.Responses.UserResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdGroup")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("TandaTanganFile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserResponses");
                });

            modelBuilder.Entity("Core.Models.Entities.FormRic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternatifSolusi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AsIsProcessRasciFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BrConfirm")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DampakMasalah")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EcsConfirm")
                        .HasColumnType("bit");

                    b.Property<string>("ExcpectedCompletionTargetFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaktorPenyebabMasalah")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HasilSetelahPerbaikan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hastag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdGroupUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permasalahan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PotensiValueCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SarmConfirm")
                        .HasColumnType("bit");

                    b.Property<string>("SolusiSaatIni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToBeProcessBusinessRasciKkiFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("FormRics");
                });

            modelBuilder.Entity("Core.Models.Entities.FormRicApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FormRicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdApprover")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFormRic")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("FormRicId");

                    b.ToTable("FormRicApprovals");
                });

            modelBuilder.Entity("Core.Models.Entities.FormRicHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditedFieldsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdEditor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFormRic")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EditorId");

                    b.ToTable("FormRicHistories");
                });

            modelBuilder.Entity("Core.Models.Entities.FormRicRollOut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompareWithAsIsHoldingProcessFiles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entitas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasDataCenterConnection")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRequiredResource")
                        .HasColumnType("bit");

                    b.Property<string>("Hashtag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdGroupUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsImplementedRequiredActivation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsJoinedDomainAdPertamina")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsingErpPertamina")
                        .HasColumnType("bit");

                    b.Property<string>("JudulAplikasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StkAsIsToBeFiles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdGroupUser");

                    b.HasIndex("IdUser");

                    b.ToTable("FormRicRollOuts");
                });

            modelBuilder.Entity("Core.Models.Entities.FormRicRollOutApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FormRicRollOutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdApprover")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFormRicRollOut")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("FormRicRollOutId");

                    b.ToTable("FormRicRollOutApprovals");
                });

            modelBuilder.Entity("Core.Models.Entities.FormRicRollOutHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditedFieldsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FormRicRollOutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdEditor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFormRicRollOut")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EditorId");

                    b.HasIndex("FormRicRollOutId");

                    b.ToTable("FormRicRollOutHistories");
                });

            modelBuilder.Entity("Core.Models.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NamaDivisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaPerusahaan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            NamaDivisi = "Enterprise Data Management",
                            NamaPerusahaan = "PT Pertamina (Persero)"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            NamaDivisi = "Business RIC",
                            NamaPerusahaan = "PT Pertamina (Persero)"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            NamaDivisi = "Strategic & Risk Management",
                            NamaPerusahaan = "PT Pertamina (Persero)"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            NamaDivisi = "Enterprise Corporate Strategy",
                            NamaPerusahaan = "PT Pertamina (Persero)"
                        });
                });

            modelBuilder.Entity("Core.Models.Entities.ReviewFormRic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Catatan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FormRicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFormRic")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleReview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FormRicId");

                    b.HasIndex("UserId");

                    b.ToTable("ReviewFormRics");
                });

            modelBuilder.Entity("Core.Models.Entities.ReviewFormRicRollOut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Catatan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FormRicRollOutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFormRicRollOut")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleReview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FormRicRollOutId");

                    b.HasIndex("UserId");

                    b.ToTable("ReviewFormRicRollOuts");
                });

            modelBuilder.Entity("Core.Models.Entities.UndanganFormRic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BrId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdBr")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdGroupUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BrId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UndanganFormRics");
                });

            modelBuilder.Entity("Core.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdGroup")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("TandaTanganFile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000001"),
                            Email = "user.member@pertamina.com",
                            IdGroup = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "User Member",
                            PasswordHash = "$2y$12$OKEN8e5STPrspBDtwA7.uOZ1JAURhlNpuyvXyl6WEomPgi2KoruXu",
                            Position = "Staff",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000002"),
                            Email = "user.pic@pertamina.com",
                            IdGroup = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Fadhil Rabbani",
                            PasswordHash = "$2y$12$OKEN8e5STPrspBDtwA7.uOZ1JAURhlNpuyvXyl6WEomPgi2KoruXu",
                            Position = "PIC",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000003"),
                            Email = "user.manager@pertamina.com",
                            IdGroup = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "User Manager",
                            PasswordHash = "$2y$12$OKEN8e5STPrspBDtwA7.uOZ1JAURhlNpuyvXyl6WEomPgi2KoruXu",
                            Position = "Manager",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000004"),
                            Email = "user.vp@pertamina.com",
                            IdGroup = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "User VP",
                            PasswordHash = "$2y$12$OKEN8e5STPrspBDtwA7.uOZ1JAURhlNpuyvXyl6WEomPgi2KoruXu",
                            Position = "Vice President",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000004"),
                            Email = "br.member@pertamina.com",
                            IdGroup = new Guid("20000000-0000-0000-0000-000000000002"),
                            Name = "BR Member",
                            PasswordHash = "$2y$12$OKEN8e5STPrspBDtwA7.uOZ1JAURhlNpuyvXyl6WEomPgi2KoruXu",
                            Position = "Staff",
                            Role = 5
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000001"),
                            Email = "br.pic@pertamina.com",
                            IdGroup = new Guid("20000000-0000-0000-0000-000000000002"),
                            Name = "BR PIC",
                            PasswordHash = "$2y$12$OKEN8e5STPrspBDtwA7.uOZ1JAURhlNpuyvXyl6WEomPgi2KoruXu",
                            Position = "PIC",
                            Role = 4
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000002"),
                            Email = "br.manager@pertamina.com",
                            IdGroup = new Guid("20000000-0000-0000-0000-000000000002"),
                            Name = "BR Manager",
                            PasswordHash = "$2y$12$OKEN8e5STPrspBDtwA7.uOZ1JAURhlNpuyvXyl6WEomPgi2KoruXu",
                            Position = "Manager",
                            Role = 6
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000003"),
                            Email = "br.vp@pertamina.com",
                            IdGroup = new Guid("20000000-0000-0000-0000-000000000002"),
                            Name = "BR VP",
                            PasswordHash = "$2y$12$OKEN8e5STPrspBDtwA7.uOZ1JAURhlNpuyvXyl6WEomPgi2KoruXu",
                            Position = "Vice President",
                            Role = 7
                        },
                        new
                        {
                            Id = new Guid("33000000-0000-0000-0000-000000000004"),
                            Email = "sarm.member@pertamina.com",
                            IdGroup = new Guid("30000000-0000-0000-0000-000000000003"),
                            Name = "SARM Member",
                            PasswordHash = "$2y$12$OKEN8e5STPrspBDtwA7.uOZ1JAURhlNpuyvXyl6WEomPgi2KoruXu",
                            Position = "Staff",
                            Role = 9
                        },
                        new
                        {
                            Id = new Guid("33000000-0000-0000-0000-000000000001"),
                            Email = "sarm.pic@pertamina.com",
                            IdGroup = new Guid("30000000-0000-0000-0000-000000000003"),
                            Name = "SARM PIC",
                            PasswordHash = "$2y$12$OKEN8e5STPrspBDtwA7.uOZ1JAURhlNpuyvXyl6WEomPgi2KoruXu",
                            Position = "PIC",
                            Role = 8
                        },
                        new
                        {
                            Id = new Guid("33000000-0000-0000-0000-000000000002"),
                            Email = "sarm.manager@pertamina.com",
                            IdGroup = new Guid("30000000-0000-0000-0000-000000000003"),
                            Name = "SARM Manager",
                            PasswordHash = "$2y$12$OKEN8e5STPrspBDtwA7.uOZ1JAURhlNpuyvXyl6WEomPgi2KoruXu",
                            Position = "Manager",
                            Role = 10
                        },
                        new
                        {
                            Id = new Guid("33000000-0000-0000-0000-000000000003"),
                            Email = "sarm.vp@pertamina.com",
                            IdGroup = new Guid("30000000-0000-0000-0000-000000000003"),
                            Name = "SARM VP",
                            PasswordHash = "$2y$12$OKEN8e5STPrspBDtwA7.uOZ1JAURhlNpuyvXyl6WEomPgi2KoruXu",
                            Position = "Vice President",
                            Role = 11
                        },
                        new
                        {
                            Id = new Guid("44000000-0000-0000-0000-000000000004"),
                            Email = "ecs.member@pertamina.com",
                            IdGroup = new Guid("40000000-0000-0000-0000-000000000004"),
                            Name = "ECS Member",
                            PasswordHash = "$2y$12$OKEN8e5STPrspBDtwA7.uOZ1JAURhlNpuyvXyl6WEomPgi2KoruXu",
                            Position = "Staff",
                            Role = 13
                        },
                        new
                        {
                            Id = new Guid("44000000-0000-0000-0000-000000000001"),
                            Email = "ecs.pic@pertamina.com",
                            IdGroup = new Guid("40000000-0000-0000-0000-000000000004"),
                            Name = "ECS PIC",
                            PasswordHash = "$2y$12$OKEN8e5STPrspBDtwA7.uOZ1JAURhlNpuyvXyl6WEomPgi2KoruXu",
                            Position = "PIC",
                            Role = 12
                        },
                        new
                        {
                            Id = new Guid("44000000-0000-0000-0000-000000000002"),
                            Email = "ecs.manager@pertamina.com",
                            IdGroup = new Guid("40000000-0000-0000-0000-000000000004"),
                            Name = "ECS Manager",
                            PasswordHash = "$2y$12$OKEN8e5STPrspBDtwA7.uOZ1JAURhlNpuyvXyl6WEomPgi2KoruXu",
                            Position = "Manager",
                            Role = 14
                        },
                        new
                        {
                            Id = new Guid("44000000-0000-0000-0000-000000000003"),
                            Email = "ecs.vp@pertamina.com",
                            IdGroup = new Guid("40000000-0000-0000-0000-000000000004"),
                            Name = "ECS VP",
                            PasswordHash = "$2y$12$OKEN8e5STPrspBDtwA7.uOZ1JAURhlNpuyvXyl6WEomPgi2KoruXu",
                            Position = "Vice President",
                            Role = 15
                        });
                });

            modelBuilder.Entity("Core.Models.Entities.FormRic", b =>
                {
                    b.HasOne("Core.Models.Entities.Group", "Group")
                        .WithMany("FormRics")
                        .HasForeignKey("GroupId");

                    b.HasOne("Core.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Models.Entities.FormRicApproval", b =>
                {
                    b.HasOne("Core.Models.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("Core.Models.Entities.FormRic", "FormRic")
                        .WithMany()
                        .HasForeignKey("FormRicId");

                    b.Navigation("Approver");

                    b.Navigation("FormRic");
                });

            modelBuilder.Entity("Core.Models.Entities.FormRicHistory", b =>
                {
                    b.HasOne("Core.Models.Entities.User", "Editor")
                        .WithMany()
                        .HasForeignKey("EditorId");

                    b.Navigation("Editor");
                });

            modelBuilder.Entity("Core.Models.Entities.FormRicRollOut", b =>
                {
                    b.HasOne("Core.Models.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("IdGroupUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Models.Entities.FormRicRollOutApproval", b =>
                {
                    b.HasOne("Core.Models.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("Core.Models.Entities.FormRicRollOut", "FormRicRollOut")
                        .WithMany("Approvals")
                        .HasForeignKey("FormRicRollOutId");

                    b.Navigation("Approver");

                    b.Navigation("FormRicRollOut");
                });

            modelBuilder.Entity("Core.Models.Entities.FormRicRollOutHistory", b =>
                {
                    b.HasOne("Core.Models.Entities.User", "Editor")
                        .WithMany()
                        .HasForeignKey("EditorId");

                    b.HasOne("Core.Models.Entities.FormRicRollOut", "FormRicRollOut")
                        .WithMany("Histories")
                        .HasForeignKey("FormRicRollOutId");

                    b.Navigation("Editor");

                    b.Navigation("FormRicRollOut");
                });

            modelBuilder.Entity("Core.Models.Entities.ReviewFormRic", b =>
                {
                    b.HasOne("Core.Models.Entities.FormRic", "FormRic")
                        .WithMany()
                        .HasForeignKey("FormRicId");

                    b.HasOne("Core.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("FormRic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Models.Entities.ReviewFormRicRollOut", b =>
                {
                    b.HasOne("Core.Models.Entities.FormRicRollOut", "FormRicRollOut")
                        .WithMany("Reviews")
                        .HasForeignKey("FormRicRollOutId");

                    b.HasOne("Core.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("FormRicRollOut");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Models.Entities.UndanganFormRic", b =>
                {
                    b.HasOne("Core.Models.Entities.User", "Br")
                        .WithMany()
                        .HasForeignKey("BrId");

                    b.HasOne("Core.Models.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("Core.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Br");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Models.Entities.User", b =>
                {
                    b.HasOne("Core.Models.Entities.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Core.Models.Entities.FormRicRollOut", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Histories");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Core.Models.Entities.Group", b =>
                {
                    b.Navigation("FormRics");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
